version: '3.8'

services:
  app:
    build: .
    image: guoogaii/ip-geoaddress-generator:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped 