name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'  # 每天运行一次
  workflow_dispatch:     # 手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Fork Repository
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Set Git User Info
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Add Upstream
      run: |
        git remote add upstream https://github.com/GuooGaii/ip-geoaddress-generator
        git fetch upstream

    - name: Merge Upstream Changes
      run: |
        git merge upstream/main --allow-unrelated-histories --no-edit

    - name: Push Changes to Fork
      run: |
        git push origin main
